

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from uuid import uuid4

import typer

from ..cli_support import emit_json, fail, fail_exception, selected_paths
from ..data_root import _is_link
from ..fsops import replace_with_retry, write_all, write_private_json
from ..models import Profile
from ..process_manager import (
    BrowserLaunchError,
    ProfileRunningError,
)
from ..profile_manager import AmbiguousProfileError, ProfileManager, ProfileNotFoundError
from ..storage import StorageError
from ..validation import ValidationError, validate_cookie_url_filter, validate_url


def _get_manager() -> ProfileManager:
    from ..cli import manager

    return manager()


def _identity_preset_kwargs(profile: Profile) -> dict[str, Any]:

    cfg = getattr(profile, "launch_config", None)
    kwargs: dict[str, Any] = {}
    if cfg is not None:
        if cfg.proxy:
            kwargs["proxy"] = cfg.proxy
        if cfg.user_agent:
            kwargs["user_agent"] = cfg.user_agent
        if cfg.locale:
            kwargs["locale"] = cfg.locale
        if cfg.timezone:
            kwargs["timezone"] = cfg.timezone
    return kwargs


def _apply_cookie_filters(
    cookies: list[dict[str, Any]],
    *,
    domains: list[str] | None,
    session_only: bool,
) -> list[dict[str, Any]]:

    result = cookies
    if domains:
        lowered = [d.strip().lower().lstrip(".") for d in domains if d.strip()]
        result = [
            c
            for c in result
            if any(
                (str(c.get("domain", "")).lower().lstrip(".") == d)
                or str(c.get("domain", "")).lower().lstrip(".").endswith("." + d)
                for d in lowered
            )
        ]
    if session_only:
        result = [c for c in result if c.get("expires", -1) == -1]
    return result


def _cookie_domain_summary(cookies: list[dict[str, Any]]) -> str:

    counts: dict[str, int] = {}
    for c in cookies:
        domain = str(c.get("domain", "")).lstrip(".") or "(none)"
        counts[domain] = counts.get(domain, 0) + 1
    if not counts:
        return ""
    ordered = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    return ", ".join(f"{domain} ({count})" for domain, count in ordered)


_NETSCAPE_FIELDS = ("domain", "include_subdomains", "path", "secure", "expires", "name", "value")


def _parse_cookie_file(raw: str, source: Path) -> list[dict[str, Any]]:

    stripped = raw.lstrip()
    if stripped.startswith("["):
        try:
            data = json.loads(stripped)
        except json.JSONDecodeError as exc:
            raise ValueError(f"invalid JSON: {exc}") from exc
        if not isinstance(data, list) or not all(isinstance(c, dict) for c in data):
            raise ValueError("JSON cookie file must be an array of cookie objects")
        for index, cookie in enumerate(data):
            if not str(cookie.get("name", "")).strip() or not isinstance(cookie.get("value"), str):
                raise ValueError(f"malformed cookie entry at index {index}: name and value are required")
            if not cookie.get("domain") and not cookie.get("url"):
                raise ValueError(f"malformed cookie entry at index {index}: 'domain' (or 'url') is required")
        return data

    cookies: list[dict[str, Any]] = []
    for line_no, line in enumerate(raw.splitlines(), start=1):
        http_only = line.startswith("#HttpOnly_")
        if http_only:
            line = line[len("#HttpOnly_") :]
        if not line.strip() or (line.startswith("#") and not http_only):
            continue
        parts = line.split("\t")
        if len(parts) != len(_NETSCAPE_FIELDS):
            raise ValueError(f"malformed cookie entry at line {line_no}: expected 7 tab-separated fields")
        domain, include_sub, path, secure, expires, name, value = parts
        if not domain or not name or include_sub not in {"TRUE", "FALSE"} or secure not in {"TRUE", "FALSE"}:
            raise ValueError(f"malformed cookie entry at line {line_no}: invalid domain, name, or flag")
        domain = ("." if include_sub == "TRUE" else "") + domain.lstrip(".")
        try:
            expires_int = int(expires)
        except ValueError as exc:
            raise ValueError(f"malformed cookie entry at line {line_no}: invalid expiry {expires!r}") from exc

        cookies.append(
            {
                "domain": domain,
                "path": path or "/",
                "secure": secure.upper() == "TRUE",
                "httpOnly": http_only,
                "expires": -1 if expires_int == 0 else expires_int,
                "name": name,
                "value": value,
            }
        )
    return cookies


def _cookies_to_netscape(cookies: list[dict[str, Any]]) -> list[str]:

    lines = ["# Netscape HTTP Cookie File", "# Generated by ProfileDock"]
    for c in cookies:
        domain = str(c.get("domain", ""))
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        if c.get("httpOnly"):
            domain = "#HttpOnly_" + domain
        path = str(c.get("path", "/")) or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = c.get("expires", -1)
        expires_field = "0" if expires == -1 else str(int(expires))
        fields = (domain, include_sub, path, secure, expires_field, c.get("name", ""), c.get("value", ""))
        if any(any(char in str(field) for char in "\t\r\n") for field in fields):
            raise ValueError("cookie fields cannot contain tabs or newlines in Netscape format")
        lines.append("\t".join(str(field) for field in fields))
    return lines


def _write_private_text(path: Path, text: str) -> None:

    target = path.expanduser().absolute()
    if _is_link(target) or (target.exists() and not target.is_file()):
        raise OSError(f"unsafe output target: {target}")
    temporary = target.with_name(f".{target.name}.{uuid4().hex}.tmp")
    try:
        fd = os.open(str(temporary), os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        try:
            write_all(fd, text.encode("utf-8"))
            os.fsync(fd)
        finally:
            os.close(fd)
        replace_with_retry(temporary, target)
    except OSError as exc:
        raise OSError(f"cannot write '{target}': {exc.strerror or exc}") from exc
    finally:
        temporary.unlink(missing_ok=True)


def list_tabs_command(
    profile_id: str = typer.Argument(..., help="Profile ID, prefix, or name."),
    json_output: bool = typer.Option(False, "--json", help="Output in JSON format."),
) -> None:
    """List open browser tabs, URLs, and titles in a running Playwright session."""
    from ..cli import _render_table, runtime_path, send_controller_command

    try:
        profile = _get_manager().resolve(profile_id)
        res = send_controller_command(
            profile.data_dir,
            cmd="tabs",
            runtime_dir=runtime_path(profile),
            auto_start_headless=False,
        )
    except (
        ProfileNotFoundError,
        AmbiguousProfileError,
        StorageError,
        ProfileRunningError,
        BrowserLaunchError,
        ValueError,
    ) as exc:
        fail_exception(exc)

    tabs = res.get("tabs", [])
    if json_output:
        emit_json("tabs", tabs)
        return

    if not tabs:
        typer.echo("No open tabs.")
        return

    rows = [["INDEX", "TITLE", "URL"]]
    for item in tabs:
        rows.append([str(item["index"]), item.get("title", "") or "(untitled)", item.get("url", "")])
    typer.echo(_render_table(rows))


def open_tab_command(
    profile_id: str = typer.Argument(..., help="Profile ID, prefix, or name."),
    url: str = typer.Argument("about:blank", help="URL to open in the new tab."),
    json_output: bool = typer.Option(False, "--json", help="Output in JSON format."),
) -> None:
    """Open a new tab dynamically in an active Playwright browser session."""
    from ..cli import runtime_path, send_controller_command

    if url != "about:blank":
        try:
            validate_url(url)
        except ValidationError as exc:
            fail_exception(exc)

    try:
        profile = _get_manager().resolve(profile_id)
        res = send_controller_command(
            profile.data_dir,
            cmd="open_tab",
            args={"url": url},
            runtime_dir=runtime_path(profile),
            auto_start_headless=True,
            **_identity_preset_kwargs(profile),
        )
    except (
        ProfileNotFoundError,
        AmbiguousProfileError,
        StorageError,
        ProfileRunningError,
        BrowserLaunchError,
        ValueError,
    ) as exc:
        fail_exception(exc)

    tab_data = res.get("tab", {})
    if json_output:
        emit_json("open-tab", tab_data)
        return

    typer.echo(f"Opened tab [{tab_data.get('index', 0)}] with URL: {tab_data.get('url', url)}")


def close_tab_command(
    profile_id: str = typer.Argument(..., help="Profile ID, prefix, or name."),
    index: int = typer.Argument(..., help="0-based tab index to close."),
    json_output: bool = typer.Option(False, "--json", help="Output in JSON format."),
) -> None:
    """Close a specific tab by its index in an active Playwright session."""
    from ..cli import runtime_path, send_controller_command

    if index < 0:
        fail("tab index must be at least 0")
    try:
        profile = _get_manager().resolve(profile_id)
        res = send_controller_command(
            profile.data_dir,
            cmd="close_tab",
            args={"index": index},
            runtime_dir=runtime_path(profile),
            auto_start_headless=False,
        )
    except (
        ProfileNotFoundError,
        AmbiguousProfileError,
        StorageError,
        ProfileRunningError,
        BrowserLaunchError,
        ValueError,
    ) as exc:
        fail_exception(exc)

    if json_output:
        emit_json(
            "close-tab",
            {"index": index, "remaining_tabs": res.get("remaining_tabs", 0)},
        )
        return

    typer.echo(f"Closed tab [{index}]. Remaining open tab(s): {res.get('remaining_tabs', 0)}")


def read_page_command(
    profile_id: str = typer.Argument(..., help="Profile ID, prefix, or name."),
    url: str | None = typer.Argument(None, help="Optional URL to navigate to before reading."),
    tab: int = typer.Option(0, "--tab", "-t", help="0-based tab index to read (default: 0)."),
    json_output: bool = typer.Option(False, "--json", help="Output in JSON format."),
) -> None:
    """Read a page's content as formatted Markdown in the terminal (headless web reader)."""
    from ..cli import runtime_path, send_controller_command

    if tab < 0:
        fail("tab index must be at least 0")
    if url:
        try:
            validate_url(url)
        except ValidationError as exc:
            fail_exception(exc)

    try:
        profile = _get_manager().resolve(profile_id)
        res = send_controller_command(
            profile.data_dir,
            cmd="read_page",
            args={"url": url, "tab": tab},
            runtime_dir=runtime_path(profile),
            auto_start_headless=True,
            **_identity_preset_kwargs(profile),
            timeout=40.0,
        )
    except (
        ProfileNotFoundError,
        AmbiguousProfileError,
        StorageError,
        ProfileRunningError,
        BrowserLaunchError,
        ValueError,
    ) as exc:
        fail_exception(exc)

    if json_output:
        emit_json(
            "read",
            {
                "url": res.get("url", ""),
                "title": res.get("title", ""),
                "content": res.get("content", ""),
                "links": res.get("links", []),
            },
        )
        return

    title = res.get("title", "")
    content = res.get("content", "")
    page_url = res.get("url", "")
    try:
        from rich.console import Console
        from rich.markdown import Markdown

        console = Console()
        if title:
            console.print(f"# {title}", style="bold cyan", markup=False)
            console.print(page_url, style="dim", markup=False)
            console.print()
        if content:
            console.print(Markdown(content))
        else:
            typer.echo("(empty page content)")
    except ImportError:
        if title:
            typer.echo(f"# {title}")
            typer.echo(page_url)
            typer.echo()
        typer.echo(content or "(empty page content)")


def _validate_capture_output(output: Path, extension: str, kind: str) -> Path:

    if output.suffix.lower() != extension:
        fail(f"{kind} output must be a {extension} file")
    if output.exists() and output.is_dir():
        fail(f"output path is a directory: {output}")
    parent = output.parent if str(output.parent) else Path(".")
    if not parent.exists():
        fail(f"output directory does not exist: {parent}")
    return output


def _send_capture_command(
    profile: Any,
    *,
    cmd: str,
    url: str | None,
    tab: int,
    output: Path,
    extra_args: dict[str, object],
) -> dict[str, Any]:
    """Send a screenshot/pdf command; raises so the caller logs the failure."""
    from ..cli import runtime_path, send_controller_command

    return send_controller_command(
        profile.data_dir,
        cmd=cmd,
        args={"url": url, "tab": tab, "output": str(output.resolve()), **extra_args},
        runtime_dir=runtime_path(profile),
        auto_start_headless=True,
        **_identity_preset_kwargs(profile),
        timeout=60.0,
    )


def screenshot_command(
    profile_id: str = typer.Argument(..., help="Profile ID, prefix, or name."),
    url: str | None = typer.Argument(None, help="Optional URL to navigate to before capturing."),
    output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="PNG file to write (default: ./<profile>-<timestamp>.png in the working directory).",
    ),
    tab: int = typer.Option(0, "--tab", "-t", help="0-based tab index to capture (default: 0)."),
    full_page: bool = typer.Option(
        False, "--full-page", "-f", help="Capture the entire scrollable page instead of the viewport."
    ),
    json_output: bool = typer.Option(False, "--json", help="Output capture metadata in JSON format."),
) -> None:
    """Capture a PNG screenshot of a page (auto-starts the profile headlessly)."""
    from ..logger import generate_correlation_id, write_log_entry

    if tab < 0:
        fail("tab index must be at least 0")
    if url:
        try:
            validate_url(url)
        except ValidationError as exc:
            fail_exception(exc)

    paths = selected_paths()
    corr_id = generate_correlation_id()
    try:
        profile = _get_manager().resolve(profile_id)
        if output is None:
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
            output = Path(f"{profile.name}-{timestamp}.png")
        output = _validate_capture_output(output.expanduser(), ".png", "screenshot")
        res = _send_capture_command(
            profile, cmd="screenshot", url=url, tab=tab, output=output, extra_args={"full_page": full_page}
        )
    except (
        ProfileNotFoundError,
        AmbiguousProfileError,
        StorageError,
        ProfileRunningError,
        BrowserLaunchError,
        ValueError,
    ) as exc:
        write_log_entry(
            log_dir=paths.logs_dir,
            level="ERROR",
            event="screenshot_failed",
            correlation_id=corr_id,
            result="failed",
            details={"error": str(exc)},
        )
        fail_exception(exc)

    write_log_entry(
        log_dir=paths.logs_dir,
        level="INFO",
        event="screenshot_captured",
        profile_id=profile.id,
        correlation_id=corr_id,
        result="success",
        details={"output": str(output), "full_page": full_page, "bytes": res.get("bytes", 0)},
    )

    if json_output:
        emit_json(
            "shot",
            {
                "output": res.get("output", str(output)),
                "url": res.get("url", ""),
                "title": res.get("title", ""),
                "bytes": res.get("bytes", 0),
                "full_page": full_page,
            },
        )
        return

    typer.echo(f"Screenshot saved: {res.get('output', output)}")
    typer.echo(f"  Page: {res.get('title', '') or res.get('url', '')}")
    typer.echo(f"  Size: {res.get('bytes', 0)} bytes")


def pdf_command(
    profile_id: str = typer.Argument(..., help="Profile ID, prefix, or name."),
    url: str | None = typer.Argument(None, help="Optional URL to navigate to before exporting."),
    output: Path | None = typer.Option(
        None,
        "--output",
        "-o",
        help="PDF file to write (default: ./<profile>-<timestamp>.pdf in the working directory).",
    ),
    tab: int = typer.Option(0, "--tab", "-t", help="0-based tab index to export (default: 0)."),
    json_output: bool = typer.Option(False, "--json", help="Output export metadata in JSON format."),
) -> None:
    """Export a page as PDF (auto-starts the profile headlessly; headless Chromium only)."""
    from ..logger import generate_correlation_id, write_log_entry

    if tab < 0:
        fail("tab index must be at least 0")
    if url:
        try:
            validate_url(url)
        except ValidationError as exc:
            fail_exception(exc)

    paths = selected_paths()
    corr_id = generate_correlation_id()
    try:
        profile = _get_manager().resolve(profile_id)
        if output is None:
            timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
            output = Path(f"{profile.name}-{timestamp}.pdf")
        output = _validate_capture_output(output.expanduser(), ".pdf", "pdf")
        res = _send_capture_command(profile, cmd="pdf", url=url, tab=tab, output=output, extra_args={})
    except (
        ProfileNotFoundError,
        AmbiguousProfileError,
        StorageError,
        ProfileRunningError,
        BrowserLaunchError,
        ValueError,
    ) as exc:
        write_log_entry(
            log_dir=paths.logs_dir,
            level="ERROR",
            event="pdf_failed",
            correlation_id=corr_id,
            result="failed",
            details={"error": str(exc)},
        )
        fail_exception(exc)

    write_log_entry(
        log_dir=paths.logs_dir,
        level="INFO",
        event="pdf_exported",
        profile_id=profile.id,
        correlation_id=corr_id,
        result="success",
        details={"output": str(output), "bytes": res.get("bytes", 0)},
    )

    if json_output:
        emit_json(
            "pdf",
            {
                "output": res.get("output", str(output)),
                "url": res.get("url", ""),
                "title": res.get("title", ""),
                "bytes": res.get("bytes", 0),
            },
        )
        return

    typer.echo(f"PDF saved: {res.get('output', output)}")
    typer.echo(f"  Page: {res.get('title', '') or res.get('url', '')}")
    typer.echo(f"  Size: {res.get('bytes', 0)} bytes")


def eval_script_command(
    profile_id: str = typer.Argument(..., help="Profile ID, prefix, or name."),
    script: str = typer.Argument(..., help="JavaScript expression to evaluate in the page."),
    tab: int = typer.Option(0, "--tab", "-t", help="0-based tab index to evaluate on (default: 0)."),
    json_output: bool = typer.Option(False, "--json", help="Output in JSON format."),
) -> None:
    """Evaluate a JavaScript expression in the active page context."""
    from ..cli import runtime_path, send_controller_command

    if tab < 0:
        fail("tab index must be at least 0")
    try:
        profile = _get_manager().resolve(profile_id)
        res = send_controller_command(
            profile.data_dir,
            cmd="eval",
            args={"script": script, "tab": tab},
            runtime_dir=runtime_path(profile),
            auto_start_headless=True,
            **_identity_preset_kwargs(profile),
        )
    except (
        ProfileNotFoundError,
        AmbiguousProfileError,
        StorageError,
        ProfileRunningError,
        BrowserLaunchError,
        ValueError,
    ) as exc:
        fail_exception(exc)

    result_val = res.get("result")
    if json_output:
        emit_json("eval", {"result": result_val})
        return

    if isinstance(result_val, (dict, list)):
        typer.echo(json.dumps(result_val, indent=2))
    else:
        typer.echo(str(result_val))


def export_cookies_command(
    profile_id: str = typer.Argument(..., help="Profile ID, prefix, or name."),
    output_file: Path | None = typer.Option(
        None, "--output", "-o", help="File to write exported JSON cookies."
    ),
    url: list[str] | None = typer.Option(
        None,
        "--url",
        "-u",
        help="URL filter(s); full URLs only (scheme required). Use --domain for bare domains.",
    ),
    domain: list[str] | None = typer.Option(
        None,
        "--domain",
        "-d",
        help="Domain filter(s); a cookie matches when its domain equals or ends with the filter.",
    ),
    session_only: bool = typer.Option(
        False, "--session-only", help="Exclude persistent cookies (those with an expiry timestamp)."
    ),
    load_file: Path | None = typer.Option(
        None,
        "--load",
        "-l",
        help="Import cookies from a JSON export or a Netscape cookies.txt file instead of exporting.",
    ),
    redact_values: bool = typer.Option(
        False,
        "--redact-values",
        help="Replace cookie values with empty strings for a metadata-only preview.",
    ),
    format: str = typer.Option(
        "json", "--format", "-f", help="Export format: 'json' (default) or 'netscape' (cookies.txt)."
    ),
    json_output: bool = typer.Option(False, "--json", help="Output in JSON format."),
) -> None:
    """Export live session cookies from browser RAM, or import cookies with --load."""
    from ..cli import runtime_path, send_controller_command

    if load_file is not None and output_file is not None:
        fail("--load and --output are mutually exclusive")
    if load_file is not None and (url or domain or session_only or redact_values):
        fail("--load cannot be combined with export filters")

    normalized_format = format.lower()
    if normalized_format not in {"json", "netscape"}:
        fail(f"unsupported format '{format}' (expected 'json' or 'netscape')")

    if load_file is not None:
        _import_cookies(profile_id, load_file, json_output=json_output)
        return

    if url:
        for u in url:
            try:
                validate_cookie_url_filter(u)
            except ValidationError as exc:
                fail_exception(exc)

    try:
        profile = _get_manager().resolve(profile_id)
        res = send_controller_command(
            profile.data_dir,
            cmd="cookies",
            args={"urls": url} if url else {},
            runtime_dir=runtime_path(profile),
            auto_start_headless=True,
            **_identity_preset_kwargs(profile),
        )
    except (
        ProfileNotFoundError,
        AmbiguousProfileError,
        StorageError,
        ProfileRunningError,
        BrowserLaunchError,
        ValueError,
    ) as exc:
        fail_exception(exc)

    cookies_list = _apply_cookie_filters(res.get("cookies", []), domains=domain, session_only=session_only)
    if redact_values:
        cookies_list = [{**c, "value": ""} for c in cookies_list]

    try:
        lines = _cookies_to_netscape(cookies_list) if normalized_format == "netscape" else None
    except ValueError as exc:
        fail_exception(exc)

    if output_file:
        try:
            if lines is not None:
                _write_private_text(output_file, "\n".join(lines) + ("\n" if lines else ""))
            else:
                write_private_json(output_file, cookies_list)
            if json_output:
                emit_json(
                    "cookies",
                    {
                        "output_file": str(output_file.expanduser().absolute()),
                        "count": len(cookies_list),
                        "format": normalized_format,
                    },
                )
            else:
                typer.echo(
                    f"Exported {len(cookies_list)} cookie(s) to '{output_file}' ({normalized_format})."
                )
                summary = _cookie_domain_summary(cookies_list)
                if summary:
                    typer.echo(f"  Domains: {summary}")
        except OSError as exc:
            fail(f"could not write cookies to '{output_file}': {exc}")
        return

    if json_output:
        emit_json("cookies", cookies_list)
        return

    if lines is not None:
        typer.echo("\n".join(lines))
    else:
        typer.echo(json.dumps(cookies_list, indent=2))


def _import_cookies(profile_id: str, load_file: Path, *, json_output: bool) -> None:

    from ..cli import runtime_path, send_controller_command

    source = load_file.expanduser()
    if not source.is_file():
        fail(f"cannot read cookie file: '{source}' does not exist or is not a file")
    try:
        raw = source.read_text(encoding="utf-8")
        set_cookies = _parse_cookie_file(raw, source)
    except (UnicodeError, ValueError, OSError) as exc:
        fail(f"invalid cookie file '{source}': {exc}")

    try:
        profile = _get_manager().resolve(profile_id)
        res = send_controller_command(
            profile.data_dir,
            cmd="set_cookies",
            args={"set_cookies": set_cookies},
            runtime_dir=runtime_path(profile),
            auto_start_headless=True,
            **_identity_preset_kwargs(profile),
        )
    except (
        ProfileNotFoundError,
        AmbiguousProfileError,
        StorageError,
        ProfileRunningError,
        BrowserLaunchError,
        ValueError,
    ) as exc:
        fail_exception(exc)

    added = int(res.get("added", len(set_cookies)))
    total = int(res.get("total_cookies", added))
    if json_output:
        emit_json(
            "cookies",
            {"output_file": str(source.absolute()), "count": added, "loaded": added, "total_cookies": total},
        )
        return
    typer.echo(f"Imported {added} cookie(s) into '{profile.name}' (jar now holds {total}).")
